### ISSUE TITLE
It is time to update sharp

### ISSUE THREAD

**Issue by mahnunchik** [m-gagne/svg2uwptiles#1]
It is time to update [sharp](https://github.com/lovell/sharp) 😉

**Comment by Brouilles** [comment]
It is why cause I have this error?
```
ERROR: https://dl.bintray.com/lovell/sharp/libvips-8.5.5-win32-x64.tar.gz status code 403
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\gaeta\Git\compta-AE\node_modules\sharp
```

**Comment by gaetandezeiraud** [comment]
Here https://github.com/m-gagne/svg2uwptiles/pull/2

**Comment by m-gagne** [comment]
Closed thanks to PR from @Brouilles.
